// Code generated by go-mock. DO NOT EDIT.
// version: go-mock v0.1.1
// source: example.go
// interface: Generics
// flags: keepctx=false unexported=false
package examples

import (
	mock "github.com/stretchr/testify/mock"
	"golang.org/x/exp/constraints"
)

func assert_MockGenerics_impl_Generics[T any]() {
	var _ Generics[T] = (*MockGenerics[T])(nil)
}

type MockGenerics[T constraints.Integer] struct {
	mock.Mock
}
